# Site settings
title: Ehcache
email: tc-oss@softwareag.com
description: Java's most widely used cache.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.ehcache.org" # the base hostname & protocol for your site
twitter_username: ehcache
github_username:  ehcache
linkedin_username: terracotta
facebook_username:  Terracotta
disqus_shortname: ehcache
timezone: GMT

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - run_cmd_each_javadoc_version.rb
  - run_proofer.sh
  - azure-pipelines.yml
  - get-deps.sh
  - add-analytics.sh

exclude_from_watch:
  - .idea/
  - _eh*/

# Build settings
markdown: kramdown


plugins:
  - jekyll-asciidoc
  - asciidoctor-diagram
  - jekyll-sitemap

# Ehcache 3.8+ uses asciidoctor-diagram rendered images
keep_files:
- documentation/3.8/images

asciidoctor:
  # We need safe since we go fetch code examples in directories lower than where the adoc file is
  safe: 0
  attributes:
    - hardbreaks!
    - source-highlighter=prettify
#    - source-highlighter=pygments
    - pygments-css=style
    - icons=font
    - sourcedir=_eh3
    - sourcedir31=_eh31
    - sourcedir32=_eh32
    - sourcedir33=_eh33
    - sourcedir34=_eh34
    - sourcedir35=_eh35
    - sourcedir36=_eh36
    - sourcedir37=_eh37
    - sourcedir38=_eh38
#needle_for_sourcedir
    - imagesdir=images
    - sectanchors
    - idprefix
    - idseparator=-

documentation:
    ehcache:
      current: "3.8"
      future: "3.9"

defaults:
  -
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      type: "drafts"
    values:
      layout: "post"
  -
    scope:
      path: "community"
      type: "pages"
    values:
      layout: "community_page"
  -
    scope:
      path: "documentation"
      type: "pages"
    values:
      layout: "docs_page"
  -
    scope:
      path: "documentation/2.7"
      type: "pages"
    values:
      layout: "docs2x_page"
      ehc_version: "2.7"
      ehc_javadoc_version: "2.7.6"
  -
    scope:
      path: "documentation/2.8"
      type: "pages"
    values:
      layout: "docs2x_page"
      ehc_version: "2.8"
      ehc_javadoc_version: "2.8.5"
  -
    scope:
      path: "documentation/3.0"
      type: "pages"
    values:
      layout: "docs30_page"
      ehc_version: "3.0"
      ehc_javadoc_version: "3.0.3"
      ehc_checkout_dir_var: "sourcedir"
  -
    scope:
      path: "documentation/3.1"
      type: "pages"
    values:
      layout: "docs30_page"
      ehc_version: "3.1"
      ehc_javadoc_version: "3.1.4"
      ehc_checkout_dir_var: "sourcedir31"
  -
    scope:
      path: "documentation/3.2"
      type: "pages"
    values:
      layout: "docs30_page"
      ehc_version: "3.2"
      ehc_javadoc_version: "3.2.3"
      ehc_checkout_dir_var: "sourcedir32"
  -
    scope:
      path: "documentation/3.3"
      type: "pages"
    values:
      layout: "docs33_page"
      ehc_version: "3.3"
      ehc_javadoc_version: "3.3.2"
      ehc_checkout_dir_var: "sourcedir33"
  -
    scope:
      path: "documentation/3.4"
      type: "pages"
    values:
      layout: "docs33_page"
      ehc_version: "3.4"
      ehc_javadoc_version: "3.4.0-docfix"
      ehc_checkout_dir_var: "sourcedir34"
  -
    scope:
      path: "documentation/3.5"
      type: "pages"
    values:
      layout: "docs35_page"
      ehc_version: "3.5"
      ehc_javadoc_version: "3.5.3"
      ehc_checkout_dir_var: "sourcedir35"
  -
    scope:
      path: "documentation/3.6"
      type: "pages"
    values:
      layout: "docs35_page"
      ehc_version: "3.6"
      ehc_javadoc_version: "3.6.1-docfix"
      ehc_checkout_dir_var: "sourcedir36"
  -
    scope:
      path: "documentation/3.7"
      type: "pages"
    values:
      layout: "docs35_page"
      ehc_version: "3.7"
      ehc_javadoc_version: "3.7.0-fixdoc"
      ehc_checkout_dir_var: "sourcedir37"
  -
    scope:
      path: "documentation/3.8"
      type: "pages"
    values:
      layout: "docs35_page"
      ehc_version: "3.8"
      ehc_javadoc_version: "3.8.0-fixdoc"
      ehc_checkout_dir_var: "sourcedir38"
